title: Train your Robot Racer | RaceLab 
description: Do you crave the thrill of the race?
theme: just-the-docs

url: https://vanzussi.github.io/racelab

aux_links:
  Template Repository: https://github.com/vanzussi/racelab
