title: Train your Robot Racer | RaceLab 
description: Do you crave the thrill of the race?
remote_theme: just-the-docs/just-the-docs

url: https://vanzussi.github.io/racelab

aux_links:
  Get Racelab: https://electric-azimuth.co.uk/racelgg

footer_content: "Copyright &copy; 2023-2299 Van Zussi."

favicon_ico: "/assets/favicon.ico"

